package com.matching.ezgg.domain.matchInfo.matchKeyword.championInfo;

import lombok.Getter;

public enum ChampionBasicInfo {
	GAREN("가렌", "Garen", ChampionRole.AD_BRUISER),
	GALIO("갈리오", "Galio", ChampionRole.TANK, ChampionRole.AP_MAGE),
	GANGPLANK("갱플랭크", "Gangplank", ChampionRole.AD_BRUISER, ChampionRole.AD_DEALER),
	GRAGAS("그라가스", "Gragas", ChampionRole.TANK, ChampionRole.AP_MAGE),
	GRAVES("그레이브즈", "Graves", ChampionRole.AD_BRUISER, ChampionRole.AD_DEALER),
	GWEN("그웬", "Gwen", ChampionRole.AP_BRUISER),
	GNAR("나르", "Gnar", ChampionRole.AD_BRUISER, ChampionRole.TANK),
	NAMI("나미", "Nami", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	NASUS("나서스", "Nasus", ChampionRole.AD_BRUISER, ChampionRole.TANK),
	NAFFIRI("나피리", "Naafiri", ChampionRole.AD_ASSASSIN),
	NAUTILUS("노틸러스", "Nautilus", ChampionRole.TANK, ChampionRole.SUPPORT),
	NOCTURNE("녹턴", "Nocturne", ChampionRole.AD_ASSASSIN),
	NUNU_WILLUMP("누누와 윌럼프", "Nunu & Willump", ChampionRole.TANK, ChampionRole.JUNGLE),
	NIDALEE("니달리", "Nidalee", ChampionRole.AP_ASSASSIN, ChampionRole.JUNGLE),
	NEKO("니코", "Neeko", ChampionRole.AP_MAGE),
	NILAH("닐라", "Nilah", ChampionRole.AD_DEALER),
	DARIUS("다리우스", "Darius", ChampionRole.AD_BRUISER),
	DIANA("다이애나", "Diana", ChampionRole.AP_BRUISER, ChampionRole.AP_ASSASSIN),
	DRAVEN("드레이븐", "Draven", ChampionRole.AD_DEALER, ChampionRole.AD_ASSASSIN),
	RYZE("라이즈", "Ryze", ChampionRole.AP_MAGE),
	RAKAN("라칸", "Rakan", ChampionRole.SUPPORT),
	RAMMUS("람머스", "Rammus", ChampionRole.TANK, ChampionRole.JUNGLE),
	LUX("럭스", "Lux", ChampionRole.AP_MAGE, ChampionRole.SUPPORT),
	RUMBLE("럼블", "Rumble", ChampionRole.AP_BRUISER, ChampionRole.AP_MAGE),
	RENATA("레나타 글라스크", "Renata Glasc", ChampionRole.SUPPORT),
	RENEKTON("레넥톤", "Renekton", ChampionRole.AD_BRUISER),
	LEONA("레오나", "Leona", ChampionRole.TANK, ChampionRole.SUPPORT),
	REKSAI("렉사이", "Rek'Sai", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	RELL("렐", "Rell", ChampionRole.TANK, ChampionRole.SUPPORT),
	RENGAR("렝가", "Rengar", ChampionRole.AD_ASSASSIN),
	LUCIAN("루시안", "Lucian", ChampionRole.AD_CARRY),
	LULU("룰루", "Lulu", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	LEBLANC("르블랑", "LeBlanc", ChampionRole.AP_ASSASSIN, ChampionRole.AP_MAGE),
	LEE_SIN("리 신", "Lee Sin", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	RIVEN("리븐", "Riven", ChampionRole.AD_BRUISER),
	LISSANDRA("리산드라", "Lissandra", ChampionRole.AP_MAGE),
	LILLIA("릴리아", "Lillia", ChampionRole.AP_BRUISER, ChampionRole.JUNGLE),
	MASTER_YI("마스터 이", "Master Yi", ChampionRole.AD_BRUISER, ChampionRole.AD_ASSASSIN),
	MAOKAI("마오카이", "Maokai", ChampionRole.TANK, ChampionRole.SUPPORT),
	MALZAHAR("말자하", "Malzahar", ChampionRole.AP_MAGE),
	MALPHITE("말파이트", "Malphite", ChampionRole.TANK, ChampionRole.AP_MAGE),
	MEL("멜", "Mell", ChampionRole.AP_DEALER),
	MORDEKAISER("모데카이저", "Mordekaiser", ChampionRole.AP_BRUISER, ChampionRole.TANK),
	MORGANA("모르가나", "Morgana", ChampionRole.AP_MAGE, ChampionRole.SUPPORT),
	MUNDO("문도 박사", "Dr. Mundo", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	MISS_FORTUNE("미스 포츈", "Miss Fortune", ChampionRole.AD_CARRY),
	MILIO("밀리오", "Milio", ChampionRole.SUPPORT),
	BARD("바드", "Bard", ChampionRole.SUPPORT),
	VARUS("바루스", "Varus", ChampionRole.AD_CARRY, ChampionRole.AP_MAGE),
	VI("바이", "Vi", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	VEIGAR("베이가", "Veigar", ChampionRole.AP_MAGE),
	VAYNE("베인", "Vayne", ChampionRole.AD_CARRY),
	VEX("벡스", "Vex", ChampionRole.AP_MAGE),
	BELVETH("벨베스", "Bel'Veth", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	VELKOZ("벨코즈", "Vel'Koz", ChampionRole.AP_MAGE),
	VOLIBEAR("볼리베어", "Volibear", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	BRAUM("브라움", "Braum", ChampionRole.TANK, ChampionRole.SUPPORT),
	BRIAR("브라이어", "Briar", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	BRAND("브랜드", "Brand", ChampionRole.AP_MAGE),
	VLADIMIR("블라디미르", "Vladimir", ChampionRole.AP_MAGE),
	BLITZCRANK("블리츠크랭크", "Blitzcrank", ChampionRole.TANK, ChampionRole.SUPPORT),
	VIEGO("비에고", "Viego", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	VIKTOR("빅토르", "Viktor", ChampionRole.AP_MAGE),
	POPPY("뽀삐", "Poppy", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	SAMIRA("사미라", "Samira", ChampionRole.AD_CARRY),
	SION("사이온", "Sion", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	SYLAS("사일러스", "Sylas", ChampionRole.AP_BRUISER, ChampionRole.AP_MAGE),
	SHACO("샤코", "Shaco", ChampionRole.AD_ASSASSIN, ChampionRole.JUNGLE),
	SENNA("세나", "Senna", ChampionRole.SUPPORT, ChampionRole.AD_CARRY),
	SERAPHINE("세라핀", "Seraphine", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	SEJUANI("세주아니", "Sejuani", ChampionRole.TANK, ChampionRole.JUNGLE),
	SETT("세트", "Sett", ChampionRole.AD_BRUISER),
	SONNA("소나", "Sona", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	SORAKA("소라카", "Soraka", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	SHEN("쉔", "Shen", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	SHYVANA("쉬바나", "Shyvana", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	SMOLDER("스몰더", "Smolder", ChampionRole.AD_CARRY),
	SWAIN("스웨인", "Swain", ChampionRole.AP_MAGE, ChampionRole.AP_BRUISER),
	SKARNER("스카너", "Skarner", ChampionRole.TANK, ChampionRole.JUNGLE),
	SIVIR("시비르", "Sivir", ChampionRole.AD_CARRY),
	XIN_ZHAO("신 짜오", "Xin Zhao", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	SYNDRA("신드라", "Syndra", ChampionRole.AP_MAGE),
	SINGED("신지드", "Singed", ChampionRole.AP_BRUISER, ChampionRole.TANK),
	THRESH("쓰레쉬", "Thresh", ChampionRole.SUPPORT, ChampionRole.TANK),
	AHRI("아리", "Ahri", ChampionRole.AP_MAGE, ChampionRole.AP_ASSASSIN),
	AMUMU("아무무", "Amumu", ChampionRole.TANK, ChampionRole.JUNGLE),
	AURELION_SOL("아우렐리온 솔", "Aurelion Sol", ChampionRole.AP_MAGE),
	IVERN("아이번", "Ivern", ChampionRole.SUPPORT, ChampionRole.JUNGLE),
	AZIR("아지르", "Azir", ChampionRole.AP_MAGE),
	AKALI("아칼리", "Akali", ChampionRole.AP_ASSASSIN),
	AKSHAN("아크샨", "Akshan", ChampionRole.AD_ASSASSIN, ChampionRole.AD_CARRY),
	AATROX("아트록스", "Aatrox", ChampionRole.AD_BRUISER),
	APHELIOS("아펠리오스", "Aphelios", ChampionRole.AD_CARRY),
	ALISTAR("알리스타", "Alistar", ChampionRole.TANK, ChampionRole.SUPPORT),
	AMBESA("암베사", "Ambesa", ChampionRole.AD_BRUISER, ChampionRole.AD_ASSASSIN),
	ANNIE("애니", "Annie", ChampionRole.AP_MAGE),
	ANIVIA("애니비아", "Anivia", ChampionRole.AP_MAGE),
	ASHE("애쉬", "Ashe", ChampionRole.AD_CARRY),
	YASUO("야스오", "Yasuo", ChampionRole.AD_BRUISER, ChampionRole.AD_CARRY),
	EKKO("에코", "Ekko", ChampionRole.AP_ASSASSIN, ChampionRole.AP_BRUISER),
	ELISE("엘리스", "Elise", ChampionRole.AP_ASSASSIN, ChampionRole.JUNGLE),
	WUKONG("오공", "Wukong", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	AURORA("오로라", "Aurora", ChampionRole.AP_DEALER),
	ORNN("오른", "Ornn", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	ORIANNA("오리아나", "Orianna", ChampionRole.AP_MAGE),
	OLAF("올라프", "Olaf", ChampionRole.AD_BRUISER),
	YONE("요네", "Yone", ChampionRole.AD_BRUISER, ChampionRole.AD_ASSASSIN),
	YORICK("요릭", "Yorick", ChampionRole.AD_BRUISER),
	UDYR("우디르", "Udyr", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	URGOT("우르곳", "Urgot", ChampionRole.AD_BRUISER),
	WARWICK("워윅", "Warwick", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	YUUMI("유미", "Yuumi", ChampionRole.SUPPORT),
	IRELIA("이렐리아", "Irelia", ChampionRole.AD_BRUISER),
	EVELYN("이블린", "Evelynn", ChampionRole.AP_ASSASSIN, ChampionRole.JUNGLE),
	EZREAL("이즈리얼", "Ezreal", ChampionRole.AD_CARRY),
	ILLAOI("일라오이", "Illaoi", ChampionRole.AD_BRUISER),
	JARVAN_IV("자르반 4세", "Jarvan IV", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	XAYAH("자야", "Xayah", ChampionRole.AD_CARRY),
	ZYRA("자이라", "Zyra", ChampionRole.AP_MAGE, ChampionRole.SUPPORT),
	ZAC("자크", "Zac", ChampionRole.TANK, ChampionRole.JUNGLE),
	JANNA("잔나", "Janna", ChampionRole.SUPPORT),
	JAX("잭스", "Jax", ChampionRole.AD_BRUISER),
	ZED("제드", "Zed", ChampionRole.AD_ASSASSIN),
	XERATH("제라스", "Xerath", ChampionRole.AP_MAGE),
	ZERI("제리", "Zeri", ChampionRole.AD_CARRY),
	JAYCE("제이스", "Jayce", ChampionRole.AD_BRUISER, ChampionRole.AD_CARRY),
	ZOE("조이", "Zoe", ChampionRole.AP_MAGE),
	ZIGGS("직스", "Ziggs", ChampionRole.AP_MAGE),
	JIN("진", "Jhin", ChampionRole.AD_CARRY),
	ZILEAN("질리언", "Zilean", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	JINX("징크스", "Jinx", ChampionRole.AD_CARRY),
	CHOGATH("초가스", "Cho'Gath", ChampionRole.TANK, ChampionRole.AP_MAGE),
	KARMA("카르마", "Karma", ChampionRole.SUPPORT, ChampionRole.AP_MAGE),
	CAMILLE("카밀", "Camille", ChampionRole.AD_BRUISER),
	KASSADIN("카사딘", "Kassadin", ChampionRole.AP_ASSASSIN, ChampionRole.AP_MAGE),
	KARTHUS("카서스", "Karthus", ChampionRole.AP_MAGE, ChampionRole.JUNGLE),
	CASSIOPEIA("카시오페아", "Cassiopeia", ChampionRole.AP_MAGE),
	KAI_SA("카이사", "Kai'Sa", ChampionRole.AD_CARRY),
	KHAZIX("카직스", "Kha'Zix", ChampionRole.AD_ASSASSIN, ChampionRole.JUNGLE),
	KATARINA("카타리나", "Katarina", ChampionRole.AP_ASSASSIN),
	KALISTA("칼리스타", "Kalista", ChampionRole.AD_CARRY),
	KENNEN("케넨", "Kennen", ChampionRole.AP_MAGE, ChampionRole.AD_CARRY),
	CAITLYN("케이틀린", "Caitlyn", ChampionRole.AD_CARRY),
	KAYN("케인", "Kayn", ChampionRole.AD_BRUISER, ChampionRole.AD_ASSASSIN),
	KAYLE("케일", "Kayle", ChampionRole.AP_MAGE, ChampionRole.AD_CARRY),
	KOGMAW("코그모", "Kog'Maw", ChampionRole.AD_CARRY),
	CORKI("코르키", "Corki", ChampionRole.AD_CARRY, ChampionRole.AP_MAGE),
	QUINN("퀸", "Quinn", ChampionRole.AD_CARRY, ChampionRole.AD_ASSASSIN),
	KSANTE("크산테", "K'Sante", ChampionRole.TANK, ChampionRole.AD_BRUISER),
	KLED("클레드", "Kled", ChampionRole.AD_BRUISER),
	QIYANA("키아나", "Qiyana", ChampionRole.AD_ASSASSIN),
	KINDRED("킨드레드", "Kindred", ChampionRole.AD_CARRY, ChampionRole.JUNGLE),
	TARIC("타릭", "Taric", ChampionRole.SUPPORT, ChampionRole.TANK),
	TALON("탈론", "Talon", ChampionRole.AD_ASSASSIN),
	TALIYAH("탈리야", "Taliyah", ChampionRole.AP_MAGE, ChampionRole.JUNGLE),
	TAHM_KENCH("탐 켄치", "Tahm Kench", ChampionRole.TANK, ChampionRole.SUPPORT),
	TRUNDLE("트런들", "Trundle", ChampionRole.AD_BRUISER, ChampionRole.TANK),
	TRISTANA("트리스타나", "Tristana", ChampionRole.AD_CARRY),
	TRYNDAMERE("트린다미어", "Tryndamere", ChampionRole.AD_BRUISER),
	TWISTED_FATE("트위스티드 페이트", "Twisted Fate", ChampionRole.AP_MAGE, ChampionRole.AD_CARRY),
	TWITCH("트위치", "Twitch", ChampionRole.AD_DEALER, ChampionRole.AP_DEALER, ChampionRole.AD_BRUISER),
	TEEMO("티모", "Teemo", ChampionRole.AP_MAGE, ChampionRole.AD_CARRY),
	PYKE("파이크", "Pyke", ChampionRole.SUPPORT, ChampionRole.AD_ASSASSIN),
	PANTHEON("판테온", "Pantheon", ChampionRole.AD_BRUISER, ChampionRole.AD_ASSASSIN),
	FIDDLESTICKS("피들스틱", "Fiddlesticks", ChampionRole.AP_MAGE, ChampionRole.JUNGLE),
	FIORA("피오라", "Fiora", ChampionRole.AD_BRUISER),
	FIZZ("피즈", "Fizz", ChampionRole.AP_ASSASSIN),
	HEIMERDINGER("하이머딩거", "Heimerdinger", ChampionRole.AP_MAGE),
	HECARIM("헤카림", "Hecarim", ChampionRole.AD_BRUISER, ChampionRole.JUNGLE),
	HWAY("흐웨이", "Hwei", ChampionRole.AP_MAGE);


	@Getter
	private final String koreanName;
	@Getter
	private final String englishName;
	@Getter
	private final ChampionRole[] championRoles;

	ChampionBasicInfo(String koreanName, String englishName, ChampionRole... championRoles) {
		this.koreanName = koreanName;
		this.englishName = englishName;
		this.championRoles = championRoles;
	}
}

