spring:
  application:
    name: ezgg
  profiles:
    default: local
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
server:
  port: 8888
